#ifndef LISTS_H
#define LISTS_H

#define ALLOW_DEBUG 1

#define TW 32 // tile width
#define TW2 (TW / 2)

//#define ENEMY_DETECTION_RADIUS (TW * 3)

#define KNOCKBACK_STRENGHT 5.0f
#define KNOCKBACK_TIME 10

#define ANIMATION_TIME 20
#define MAX_INVENTORY_SLOTS 6

#define PLAYER_BASE_SPEED 2.0f
#define PLAYER_MAX_SPEED (PLAYER_BASE_SPEED * 2.0f)

#define HP_REGEN_TIME (2 * 60)
#define MANA_REGEN_TIME (4 * 60)

#define INITIAL_AI_DELAY 60

#define FINAL_FLOOR 30

#define ESCAPE_TIME (60 * FINAL_FLOOR * 30)

namespace GAMESTATE { enum { MENU, PLAYING, ENDING, EXIT }; }

namespace TILE { enum { _VOID_, FLOOR, WALL, STAIRS_UP, STAIRS_DOWN }; }
namespace ENEMY { enum { RAT, SLIME, GOBLIN, IMP, SKELETON, SKELETON_ARCHER, SKELETON_WARRIOR, GHOST, DEATH_BLADE, MIMIC, DEATH_WIZARD, DRAGON, REAPER, BOSS, COUNT }; }

namespace ATTRIBUTE { enum { STRENGTH, DEXTERITY, VITALITY, MAGIC, COUNT }; }
namespace ENEMY_STATE { enum { SLEEPING, WANDERING, ALERT, COUNT }; }

namespace PROJECTILE { enum { ARROW, KNIFE, FIREBOLT, FIREBALL, FROSTBOLT, FREEZING_CLOUD, LIGHTNING, CHAIN_LIGHTNING, EXPLOSION_POTION, COUNT }; }

namespace SECONDARY_EFFECT { enum { NONE, FREEZING }; }

#endif
